pub const PADDLE_DIST_FROM_SIDES: u8 = 6;

pub const PADDLE_ACCEL: f16 = 0.7;
pub const PADDLE_MAX_VEL: f16 = 4.0;
pub const PADDLE_NO_MOVE_DECAY_RATE: f16 = 0.7;

pub const DAMPEN_BOUNCE: f16 = 0.95;
pub const BALL_BOUNCEBACK_VX_MULT: f16 = 1.1;
pub const PADDLE_TRANSFER_VY_MULT: f16 = 0.12;
pub const BALL_MAX_VX: f16 = 5.5;

pub const RESTART_FRAME_WAIT: u32 = 120;

pub const CPU_TARGET_SPOT_TOL: f16 = 15;

pub const PADDLE_HIT_ANIM_DURATION = 10;
pub const PADDLE_BOUNCEBACK_DIST = 2;

pub const PADDLE_LUNGE_CATCHBACK_DURATION = 12;

pub const PADDLE_LUNGE_MULT: f16 = 1.4;
pub const PADDLE_CATCHBACK_SPEED_MULT: f16 = 0.7;
pub const PADDLE_CATCHBACK_SPIN_MULT: f16 = 1.5;

pub const SMOKE_START_VEL: f16 = 2;
pub const SMOKE_DECEL_MULT: f16 = 0.8;
pub const N_SMOKES_RINGBUFFER = 30;

pub const SMOKE_DURATION: u16 = 20;
pub const SMOKE_OFFSET_Y: f16 = 0;
pub const BALL_SMOKE_MULT: f16 = 0.3;

pub const GAME_NAME = "PING";

pub const BALL_SPIN_VAL_MULT = 5;
pub const BALL_SPIN_ACCEL_MULT = 0.15;
pub const BALL_SPIN_GROWTH_MULT = 0.03;

pub const BALL_SPIN_OFF_WALL_REDUCTION_MULT = 0.7;
pub const BALL_SPIN_CAP_OFF_WALL_REDUCTION_MULT = 0.3;

pub const BALL_SMOKE_INTERVAL = 10;
pub const BALL_SMOKE_OUTSPEED_MULT = 1;

pub const LARGE_NUM_FOR_SEEDING_MOD: u16 = 50000;

pub const SERVE_ANGLE_VARIATION = 60;
pub const SERVE_MAGNITUDE = 1.3;

pub const TITLE_LOC = 60;

pub const SMOKE_PADDLE_OFFSET_MULT = 0.6;
pub const SMOKE_VX_OFFSET_MULT = 0.3;

pub const HOVER_DISPLAY_X = 30;
pub const HOVER_DISPLAY_Y = 60;

pub const HOVER_DISPLAY_SETTINGS_Y = 90;

pub const HOVER_DISPLAY_Y_DIST_BETWEEN_LINES = 10;

pub const PADDLE_RANDOM_VY_MULT = 0.02;

pub const VERSION = "v0.3.0";

pub const BOOTUP_TIME = 50;

pub const CURSOR_BLINK_DURATION = 20;
